Dynatrace/css-groundhog

- README.md
- gulpfile.js
- package.json
> Codeship integration, fixes #1

- docs/_templates/layouts/default.hbs
- docs/_templates/partials/ga.hbs
Add at least google analytics to get some insight in how traffic behaves.
> Google analytics

- gulpfile.js
Critical --> goes directly into master
> fix(js): js was not included in build

- src/expandable/expandable.js
> feat(expandable): initialized state and function

- src/radiobutton/radiobutton.scss
- src/radiobutton/samples/00-standard.html
https://github.com/Dynatrace/css-groundhog/issues/27
> fixed radio btn bug - wooohooo

- docs/_assets/images/brand/navicons/textarea.svg
> feat(textarea): added navicon for textarea

- src/checkbox/checkbox.scss
- src/radiobutton/radiobutton.scss
> fix(checkbox): fixed styling bug of checkbox and radiobutton

- docs/_pages/download.md
- docs/_pages/index.md
- docs/_templates/partials/header.hbs
- gulpfile.js
- package.json
* Adds `package` gulp task that creates zip file of `main.js` and `main.css`
* Adds download page with usage options
* Adds conversion tracking GA event when downloading groundhog.
> Complete build for download

- src/table/table.scss
> fix(table): added margin-bottom to table

- src/expandable/expandable.scss
> fix(expandable): fixed positioning of expandable-trigger icon

- package.json
This allows you to build groundhog with Gulp.
> Added missing dev dependency

- src/icons/README.md
change visibility settings in documentation
> fix(doc): fix visibility doc for icons

- .gitignore
- build/plugins/addmeta.js
- gulpfile.js
- package.json
Creates a gulp publish task with:
- replace-asset-urls --> so everything goes to assets.dynatrace.com in the CDN
- package --> creating a download
- upload-s3 --> uploading to S3 using AWS credentials stored in environment variables
Fixes #4
> Cdn upload

- docs/_pages/download.md
- gulpfile.js
> chore(download): adding download documentation

- src/sidebar/README.md
> fix(doc): correct links for expandable

- src/sidebar/README.md
> chore(content): fix broken link in sidebar doc

- .npmignore
- package.json
Waiting for first true publish to merge this one.
fixes #90
> groundhog ready for NPM, fixes #90

- docs/_assets/images/brand/navicons/loading.svg
- src/common/_colors.scss
- src/loading/README.md
- src/loading/loading.scss
- src/loading/samples/00-small.html
- src/loading/samples/01-standard.html
- src/loading/samples/02-standard-with-text.html
- src/main.scss
This is the first version. 
The next step is to extend this with the following examples:
* Loading spinner in a button
* Loading spinner in an input
> feat(loading spinner): loading spinner examples and basic styling

- docs/_assets/images/brand/navicons/pagination.svg
text in thumbnail was not expanded.
> fix(doc): expand thumbnail for pagination

- .gitignore
- docs/_pages/index.md
- gulpfile.js
- package.json
Generates changelog from commit messages and takes versions from git tags. 
I will tag the previous versions as I can. We will have to tag incremental versions for the changelog to be accurate. 
Tackles #140
> Changelog generator

- src/expandable/README.md
- src/expandable/expandable.js
- src/expandable/expandable.scss
- src/expandable/samples/02-expandable-separated.html
- src/expandable/samples/03-expandable-group.html
- src/js-common-components/accordion.js
- src/navbar/navbar.js
- src/navbar/navbar.scss
- src/sidebar/README.md
- src/sidebar/samples/00-easy-sidebar.html
- src/sidebar/samples/01-expandable.html
- src/sidebar/sidebar.scss
- src/table-expandable/README.md
- src/table-expandable/samples/00-table-expandable.html
- src/table-expandable/samples/01-table-expandable.html
- src/table-expandable/samples/02-table-expandable.html
- src/table-expandable/samples/03-table-expandable.html
- src/table-expandable/samples/04-table-expandable.html
- src/table-expandable/table-expandable.scss
Removed `is-expanded` state and replaced it with `is-active`. For the active/selected/current menu item we now use `is-current`.
Also updated the documentation.
> Active states

- package.json
- src/list/list.scss
specificity of themed overrides have been adjusted to apply the theme colors in lists.
> Unordered list themes

- package.json
> bump to 1.0.0

- src/common/_label.scss
- src/main.scss
- src/progressbar/README.md
- src/progressbar/progressbar.scss
- src/progressbar/samples/00-standard.html
- src/progressbar/samples/01-with-over-under.html
- src/progressbar/samples/02-with-over-under-unit.html
Progress bar implementation for #164
> feat(progressbar):basic progressbar styling

- src/base/base.scss
- src/layout/islands.scss
fix for: https://github.com/Dynatrace/css-groundhog/issues/166
and: https://github.com/Dynatrace/css-groundhog/issues/167
> issue #166: layout bug of overflowing code blocks

- docs/_pages/changelog.md
- package.json
- src/breadcrumbs/breadcrumbs.scss
- src/navbar/navbar.scss
- src/navbar/samples/04-nav-secondary-subnav.html
- src/navbar/samples/05-nav-secondary-breadcrumbs.html
Fixes for #187 
Base branch is up for discussion
> Fix nav alignment

- docs/_pages/changelog.md
- docs/_pages/test-pages/component-test-page.md
- src/expandable/expandable.js
- src/expandable/expandable.scss
- src/main.js
- src/navbar/README.md
- src/navbar/navbar.js
- src/navbar/navbar.scss
- src/navbar/samples/02-item-right.html
- src/navbar/samples/03-nav-secondary.html
- src/navbar/samples/04-nav-secondary-subnav.html
- src/navbar/samples/05-nav-secondary-breadcrumbs.html
- src/subnav/samples/01-subnav.html
- src/subnav/samples/02-subnav-expand.html
- src/subnav/samples/03-subnav-theme-blue.html
- src/subnav/samples/04-subnav-theme-purple.html
- src/subnav/samples/05-subnav-theme-royalblue.html
- src/subnav/samples/06-subnav-theme-green.html
- removed second anchor of primary nav items, updated examples and documentation
> Navigation update

- docs/_assets/images/brand/navicons/buttongroup.svg
- src/buttongroup/README.md
- src/buttongroup/buttongroup.scss
- src/buttongroup/samples/00-buttongroup-simple.html
- src/buttongroup/samples/01-buttongroup-active.html
- src/buttongroup/samples/02-buttongroup-theme-blue.html
- src/buttongroup/samples/03-buttongroup-theme-purple.html
- src/buttongroup/samples/04-buttongroup-theme-royalblue.html
- src/buttongroup/samples/05-buttongroup-theme-green.html
- src/main.scss
Initial implementation of button group.
> feat(buttongroup): initial implementation of buttongroup

- docs/_assets/images/brand/navicons/progresscircle.svg
- src/main.js
- src/main.scss
- src/progresscircle/README.md
- src/progresscircle/progresscircle.js
- src/progresscircle/progresscircle.scss
- src/progresscircle/samples/00-standard.html
- src/progresscircle/samples/01-bold-circle.html
- src/progresscircle/samples/02-no-js-progress.html
- src/progresscircle/samples/03-js-progress.html
- src/progresscircle/samples/04-with-icon.html
- src/progresscircle/samples/05-warning.html
Implements the progress circle in various states.
> feat(progresscircle): Initial implementation progresscircle

- docs/_pages/index.md
@katrin-freihofner please consider adding this to 6.0 release
> Remove ruxit reference
